name: echostream
description: A retro Sony Walkman-inspired music player
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  youtube_explode_dart: ^2.4.2
  file_picker: ^10.2.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/lofi.mp3
    - assets/images/walkman_background.jpg
    - assets/fonts/OCRA.ttf
  fonts:
    - family: OCRA
      fonts:
        - asset: assets/fonts/OCRA.ttf